image:
  file: .gitpod/Dockerfile

tasks:
  - init: |
      .gitpod/scripts/ddev-download-images.sh
      .gitpod/scripts/ddev-setup.sh
      .gitpod/scripts/drupal-setup.sh
      .gitpod/scripts/nuxt-setup.sh
    command: |
      .gitpod/scripts/ddev-setup.sh
      .gitpod/scripts/ddev-config.sh
      cd nuxt && yarn dev

ports:
  # DDev - direct-bind https port
  - port: 2222
    onOpen: ignore
  # Nuxt - Web
  - port: 3000
    onOpen: ignore
    visibility: public
  # DDev - local db clients
  - port: 3306
    onOpen: ignore
  # DDev - MailHog
  - port: 8025
    onOpen: ignore
  # DDev - phpMyAdmin
  - port: 8036
    onOpen: ignore
  # DDev - Web
  - port: 8080
    onOpen: ignore
    visibility: public
  # DDev - xdebug port
  - port: 9000
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true

vscode:
  extensions:
    - octref.vetur
    - editorconfig.editorconfig
