enabled: true
outage_action: 0
overridden_schemes: {  }
scan_mode: 1
verbosity: 0
mode_executable:
  executable_path: /usr/bin/clamscan
  executable_parameters: ''
mode_daemon_tcpip:
  hostname: clamav.sdp-central-clamav-master.svc.cluster.local
  port: 3310
mode_daemon_unixsocket:
  unixsocket: /var/clamav/clamd
